config/routes.rb
Rails.application.routes.draw do
  root "movies#index"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :movies do 
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :genres

  resources :users
  get "signup" => "users#new"

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"

end

app/models/genre.rb
class Genre < ApplicationRecord
  before_save :set_slug 

  has_many :characterizations, dependent: :destroy
  has_many :movies, through: :characterizations
  
  validates :name, presence: true, uniqueness: true

  def to_param
    slug
  end

  private 

  def set_slug
    self.slug = name.parameterize
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  before_action :require_signin
  before_action :require_admin, except: [ :index, :show ]
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  def index
    @genres = Genre.all

  end
  
  def new
    @genre = Genre.new
  end

  def show
    @movies = @genre.movies
  end

  def create 
    @genre = Genre.new(genre_params)
    if @genre.save 
      redirect_to genres_path, notice: "Genre successfully created!"
    else 
      render :new
    end
  end

  def edit 
  end

  def update
		if @genre.update(genre_params)
			redirect_to genres_path, notice: "Genre successfully updated!" 
		else 
			render :edit
		end
	end

  def destroy
    @genre.destroy
    redirect_to @genre, alert: "Genre deleted"

  end

  private

  def set_genre 
    @genre = Genre.find_by!(slug: params[:id])
  end

	def genre_params
		params.require(:genre).permit(:name)
	end

end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model:genre, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.submit %>
<% end %>

app/views/genres/edit.html.erb
<h1>Edit Genre <%= @genre.name %></h1>
<%= render "form", genre:@genre %>

app/views/genres/index.html.erb
<h1>Genres</h1>
<section class="genres">
  <% @genres.each do |g| %>
    <%= link_to g do %>
      <div class="genre">
        <span><%= g.name %></span>
      </div>
    <% end %>
  <% end %>
</section>
<section class="admin">
  <%= link_to "Add New Genre", new_genre_path, class: "button" %>
</section>

app/views/genres/new.html.erb
<h1>Add New Genre</h1>
<%= render "form", genre:@genre %>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>
<% if @movies.present? %>
  <h2>Movies</h2>
  <% @movies.each do |movie| %>
    <%= image_tag movie.image_file_name %>
  <% end %>
<% end %>
<% if current_user_admin? %>
<section class="admin">
  <%= link_to "Edit Genre", edit_genre_path(@genre), class: "button" %>
  <%= link_to "Delete Genre", genre_path(@genre), method: :delete, class: "button" %>
</section>
<% end %>